name: Pull request checks

on:
  pull_request:
    branches:
      - V2

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.1
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: install
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build
        env:
         NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}

  code_style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        style-command:
          - lint
          - prettier
          - typecheck
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.1
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: install
        run: yarn install --frozen-lockfile
      - name: check
        run: yarn ${{ matrix.style-command }}
